spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url? 'coupon_db' ??? ?? ??? ??? MySQL DB ??? ??? ??? ???.
    url: jdbc:mysql://localhost:3306/coupon_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root # ??? MySQL ??
    password: password # ??? MySQL ????

  jpa:
    hibernate:
      ddl-auto: update # ??? ?? ? ??? ?? ????
    show-sql: true # ???? SQL? ??? ??
    properties:
      hibernate:
        format_sql: true # SQL? ?? ?? ??